//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente.Sinai {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntRol", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class EntRol : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdRolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RolField;
        
        private bool ActiveField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdRol {
            get {
                return this.IdRolField;
            }
            set {
                if ((this.IdRolField.Equals(value) != true)) {
                    this.IdRolField = value;
                    this.RaisePropertyChanged("IdRol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Rol {
            get {
                return this.RolField;
            }
            set {
                if ((object.ReferenceEquals(this.RolField, value) != true)) {
                    this.RolField = value;
                    this.RaisePropertyChanged("Rol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Sinai.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name ListaResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Lista", ReplyAction="*")]
        Cliente.Sinai.ListaResponse Lista(Cliente.Sinai.ListaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Lista", ReplyAction="*")]
        System.Threading.Tasks.Task<Cliente.Sinai.ListaResponse> ListaAsync(Cliente.Sinai.ListaRequest request);
        
        // CODEGEN: Generating message contract since element name rol from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        Cliente.Sinai.AgregarResponse Agregar(Cliente.Sinai.AgregarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        System.Threading.Tasks.Task<Cliente.Sinai.AgregarResponse> AgregarAsync(Cliente.Sinai.AgregarRequest request);
        
        // CODEGEN: Generating message contract since element name DetailsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Details", ReplyAction="*")]
        Cliente.Sinai.DetailsResponse Details(Cliente.Sinai.DetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Details", ReplyAction="*")]
        System.Threading.Tasks.Task<Cliente.Sinai.DetailsResponse> DetailsAsync(Cliente.Sinai.DetailsRequest request);
        
        // CODEGEN: Generating message contract since element name rol from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar", ReplyAction="*")]
        Cliente.Sinai.ActualizarResponse Actualizar(Cliente.Sinai.ActualizarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar", ReplyAction="*")]
        System.Threading.Tasks.Task<Cliente.Sinai.ActualizarResponse> ActualizarAsync(Cliente.Sinai.ActualizarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        void Eliminar(int IdRol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        System.Threading.Tasks.Task EliminarAsync(int IdRol);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Lista", Namespace="http://tempuri.org/", Order=0)]
        public Cliente.Sinai.ListaRequestBody Body;
        
        public ListaRequest() {
        }
        
        public ListaRequest(Cliente.Sinai.ListaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListaRequestBody {
        
        public ListaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Cliente.Sinai.ListaResponseBody Body;
        
        public ListaResponse() {
        }
        
        public ListaResponse(Cliente.Sinai.ListaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Cliente.Sinai.EntRol[] ListaResult;
        
        public ListaResponseBody() {
        }
        
        public ListaResponseBody(Cliente.Sinai.EntRol[] ListaResult) {
            this.ListaResult = ListaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Agregar", Namespace="http://tempuri.org/", Order=0)]
        public Cliente.Sinai.AgregarRequestBody Body;
        
        public AgregarRequest() {
        }
        
        public AgregarRequest(Cliente.Sinai.AgregarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Cliente.Sinai.EntRol rol;
        
        public AgregarRequestBody() {
        }
        
        public AgregarRequestBody(Cliente.Sinai.EntRol rol) {
            this.rol = rol;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarResponse", Namespace="http://tempuri.org/", Order=0)]
        public Cliente.Sinai.AgregarResponseBody Body;
        
        public AgregarResponse() {
        }
        
        public AgregarResponse(Cliente.Sinai.AgregarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AgregarResponseBody {
        
        public AgregarResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Details", Namespace="http://tempuri.org/", Order=0)]
        public Cliente.Sinai.DetailsRequestBody Body;
        
        public DetailsRequest() {
        }
        
        public DetailsRequest(Cliente.Sinai.DetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IdRol;
        
        public DetailsRequestBody() {
        }
        
        public DetailsRequestBody(int IdRol) {
            this.IdRol = IdRol;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Cliente.Sinai.DetailsResponseBody Body;
        
        public DetailsResponse() {
        }
        
        public DetailsResponse(Cliente.Sinai.DetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Cliente.Sinai.EntRol DetailsResult;
        
        public DetailsResponseBody() {
        }
        
        public DetailsResponseBody(Cliente.Sinai.EntRol DetailsResult) {
            this.DetailsResult = DetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Actualizar", Namespace="http://tempuri.org/", Order=0)]
        public Cliente.Sinai.ActualizarRequestBody Body;
        
        public ActualizarRequest() {
        }
        
        public ActualizarRequest(Cliente.Sinai.ActualizarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Cliente.Sinai.EntRol rol;
        
        public ActualizarRequestBody() {
        }
        
        public ActualizarRequestBody(Cliente.Sinai.EntRol rol) {
            this.rol = rol;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarResponse", Namespace="http://tempuri.org/", Order=0)]
        public Cliente.Sinai.ActualizarResponseBody Body;
        
        public ActualizarResponse() {
        }
        
        public ActualizarResponse(Cliente.Sinai.ActualizarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ActualizarResponseBody {
        
        public ActualizarResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : Cliente.Sinai.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Cliente.Sinai.WebServiceSoap>, Cliente.Sinai.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente.Sinai.ListaResponse Cliente.Sinai.WebServiceSoap.Lista(Cliente.Sinai.ListaRequest request) {
            return base.Channel.Lista(request);
        }
        
        public Cliente.Sinai.EntRol[] Lista() {
            Cliente.Sinai.ListaRequest inValue = new Cliente.Sinai.ListaRequest();
            inValue.Body = new Cliente.Sinai.ListaRequestBody();
            Cliente.Sinai.ListaResponse retVal = ((Cliente.Sinai.WebServiceSoap)(this)).Lista(inValue);
            return retVal.Body.ListaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente.Sinai.ListaResponse> Cliente.Sinai.WebServiceSoap.ListaAsync(Cliente.Sinai.ListaRequest request) {
            return base.Channel.ListaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente.Sinai.ListaResponse> ListaAsync() {
            Cliente.Sinai.ListaRequest inValue = new Cliente.Sinai.ListaRequest();
            inValue.Body = new Cliente.Sinai.ListaRequestBody();
            return ((Cliente.Sinai.WebServiceSoap)(this)).ListaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente.Sinai.AgregarResponse Cliente.Sinai.WebServiceSoap.Agregar(Cliente.Sinai.AgregarRequest request) {
            return base.Channel.Agregar(request);
        }
        
        public void Agregar(Cliente.Sinai.EntRol rol) {
            Cliente.Sinai.AgregarRequest inValue = new Cliente.Sinai.AgregarRequest();
            inValue.Body = new Cliente.Sinai.AgregarRequestBody();
            inValue.Body.rol = rol;
            Cliente.Sinai.AgregarResponse retVal = ((Cliente.Sinai.WebServiceSoap)(this)).Agregar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente.Sinai.AgregarResponse> Cliente.Sinai.WebServiceSoap.AgregarAsync(Cliente.Sinai.AgregarRequest request) {
            return base.Channel.AgregarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente.Sinai.AgregarResponse> AgregarAsync(Cliente.Sinai.EntRol rol) {
            Cliente.Sinai.AgregarRequest inValue = new Cliente.Sinai.AgregarRequest();
            inValue.Body = new Cliente.Sinai.AgregarRequestBody();
            inValue.Body.rol = rol;
            return ((Cliente.Sinai.WebServiceSoap)(this)).AgregarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente.Sinai.DetailsResponse Cliente.Sinai.WebServiceSoap.Details(Cliente.Sinai.DetailsRequest request) {
            return base.Channel.Details(request);
        }
        
        public Cliente.Sinai.EntRol Details(int IdRol) {
            Cliente.Sinai.DetailsRequest inValue = new Cliente.Sinai.DetailsRequest();
            inValue.Body = new Cliente.Sinai.DetailsRequestBody();
            inValue.Body.IdRol = IdRol;
            Cliente.Sinai.DetailsResponse retVal = ((Cliente.Sinai.WebServiceSoap)(this)).Details(inValue);
            return retVal.Body.DetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente.Sinai.DetailsResponse> Cliente.Sinai.WebServiceSoap.DetailsAsync(Cliente.Sinai.DetailsRequest request) {
            return base.Channel.DetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente.Sinai.DetailsResponse> DetailsAsync(int IdRol) {
            Cliente.Sinai.DetailsRequest inValue = new Cliente.Sinai.DetailsRequest();
            inValue.Body = new Cliente.Sinai.DetailsRequestBody();
            inValue.Body.IdRol = IdRol;
            return ((Cliente.Sinai.WebServiceSoap)(this)).DetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente.Sinai.ActualizarResponse Cliente.Sinai.WebServiceSoap.Actualizar(Cliente.Sinai.ActualizarRequest request) {
            return base.Channel.Actualizar(request);
        }
        
        public void Actualizar(Cliente.Sinai.EntRol rol) {
            Cliente.Sinai.ActualizarRequest inValue = new Cliente.Sinai.ActualizarRequest();
            inValue.Body = new Cliente.Sinai.ActualizarRequestBody();
            inValue.Body.rol = rol;
            Cliente.Sinai.ActualizarResponse retVal = ((Cliente.Sinai.WebServiceSoap)(this)).Actualizar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente.Sinai.ActualizarResponse> Cliente.Sinai.WebServiceSoap.ActualizarAsync(Cliente.Sinai.ActualizarRequest request) {
            return base.Channel.ActualizarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente.Sinai.ActualizarResponse> ActualizarAsync(Cliente.Sinai.EntRol rol) {
            Cliente.Sinai.ActualizarRequest inValue = new Cliente.Sinai.ActualizarRequest();
            inValue.Body = new Cliente.Sinai.ActualizarRequestBody();
            inValue.Body.rol = rol;
            return ((Cliente.Sinai.WebServiceSoap)(this)).ActualizarAsync(inValue);
        }
        
        public void Eliminar(int IdRol) {
            base.Channel.Eliminar(IdRol);
        }
        
        public System.Threading.Tasks.Task EliminarAsync(int IdRol) {
            return base.Channel.EliminarAsync(IdRol);
        }
    }
}
